### ISSUE TITLE
Catbombing after latest update

### ISSUE THREAD

**Issue by strongestFairy** [KanColleTool/KanColleTool#128]
Version: 9.4  (9.5 download link is broken), OS: Win7x64

Problem: A lot of catbombing during play after the latest event update. Can't play even 10 minutes.

Workaround:
1. Cleared cache
2. Got new API link
3. Disabled translation.
Nothing helped :-(   The friend of mine uses the 9.4 too and faces the same problem.

Does someone faced the same problem?

**Comment by uppfinnarn** [comment]
Try 0.9.5 now, the download is fixed.

**Comment by strongestFairy** [comment]
Downloaded and tried.

The problem is still here. The most often catbombing happens when I try to manage my ships or check the quest list.
When I play via API link directly in Firefox browser I do not meet any problems.

**Comment by uppfinnarn** [comment]
This is strange. Does the same thing happen if you have translation disabled?

**Comment by strongestFairy** [comment]
Yes. I've checked one more time. Disabled translation, restarted the client. And got and error very soon.
![catbomb](http://i.imgur.com/C9sQvFK.png)

**Comment by uppfinnarn** [comment]
Can you check with Wireshark, to see if the requests are flowing properly?

Also, of course, this happens if your API link is invalid, but if you can play with Firefox that can't be it...

**Comment by strongestFairy** [comment]
Made a Wireshark trace: http://www.mediafire.com/download/jar9eklybf8uxf8/kct9.5.pcapng
Packet with API link deleted from this trace.

**Comment by uppfinnarn** [comment]
This is strange - it keeps going like usual all the way until the last bit there... then it sends three RST packets, indicating a closed socket ("connection reset by peer", as it's usually worded).

I'm going out on a limb here, but what happens if you recompile the viewer with a different user agent, in case this is something DMM are doing on purpose?

**Comment by strongestFairy** [comment]
I tried to compiler Viewer some time before but failed at some point. I'm not strong with programming >.>
Maybe it can be done with some external tool like Fiddler http proxy...

**Comment by uppfinnarn** [comment]
Hm. @SoftwareGuy, can you give it a shot instead, if you have a Windows machine handy?

(Assuming Windows, since the Mac download should have been working around the time you posted the issue.)

**Comment by SunDwarf** [comment]
Just a note, you need to get a new API token now (your current one begins with 4add.)

**Comment by strongestFairy** [comment]
@SunDwarf Thank you. I know this and already made a new one. API link is repeated inside each http request.

**Comment by Yukariin** [comment]
I have randomly catscreen too, I rebuild it with `Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)` and test.

**Comment by uppfinnarn** [comment]
What does Flash Projector do? Can you compare Wireshark captures between the two?

**Comment by Yukariin** [comment]
Nope, still have catscreen with changed UA.

**Comment by SoftwareGuy** [comment]
Hmm. I wonder if we have a regression or something in the APi changed.
Hard to tell without the game actually stating the error (like DMM will even do that...)

Will test 0.9.5 when I log onto my workstation.

**Comment by uppfinnarn** [comment]
It seems like something serverside to me. I can't think of any way we could be causing the server to send RST packets by accident :/

**Comment by SunDwarf** [comment]
The RST packets in the dump are client-side.

**Comment by kevin01523** [comment]
hmm my last clone doesnt get cat errors 0.9.4

**Comment by strongestFairy** [comment]
@kevin01523 could you share your binary files? I'll test them.

**Comment by kevin01523** [comment]
http://www.mediafire.com/download/e9ahv11s74so19a/KanColleTool_qt_5.5.rar

**Comment by Yukariin** [comment]
Yep, I can confirm RST flag **from server** on 093-095 (Linux)

**Comment by strongestFairy** [comment]
I can confirm that @kevin01523 version 9.4 is quite stable. I believe that someone should inspect the code difference between two versions -_-

**Comment by Yukariin** [comment]
@strongestFairy difference between 094 and 095 - missing ssl libs.

**Comment by strongestFairy** [comment]
@Yukariin I think we should ask @kevin01523 which source code version he used for compilation of this build.

**Comment by kevin01523** [comment]
my source is just a clone of kancolletool from august 7 which dont have the XP fix i dont know why that did not get pulled that time or an earlier version of the submodules was pulled

**Comment by strongestFairy** [comment]
It is all very strange -___-"  case official 9.4 worked nice till Event game update.
@kevin01523 is this version is still available on your workstation? Could you push it to your github fork?

**Comment by Yukariin** [comment]
http://www.mediafire.com/download/v6yat1ou6qdwn5q/095_linux.pcapng
Here my trace from 094 tag

**Comment by kevin01523** [comment]
git says im behind 3 commits from current master

**Comment by strongestFairy** [comment]
Made some exploration with @kevin01523 binaries.
During play it faces RST flag from server side too but session keeps alive:
![kevin_trace](http://i.imgur.com/sj7JZz2.png)

The same query but for official 9.5 build, session meets catbomb:
![095_trace](http://i.imgur.com/lshByHs.png)

The difference is in additional SYN packet in kevin's build. I see it every time before server's RST packet.

**Comment by strongestFairy** [comment]
@kevin01523 it looks like your build is not only "3 commits behind current muster" >.>
![pic](http://i.imgur.com/DnigRsF.png)
Also Viewer do not use the official remote server for translation, but some old copy from http://kevin01523.github.io/en.json
But anyway @all we need to find why Viewer's network behavior has changed!

**Comment by SunDwarf** [comment]
@strongestFairy Can you do the binary comparison with the same server?

**Comment by SoftwareGuy** [comment]
I'll build another version of 0.9.5 today, other pulling in the latest stuff, even if its a test build.
Network debugging is a PITA but eh, we have to come to the bottom of this.

**Comment by uppfinnarn** [comment]
Hm, just for completeness' sake, could you try a build from the `rewrite` branch of the viewer as well? On the off chance that the problem is gone there, we may be able to figure out what's changed between them.

**Comment by SoftwareGuy** [comment]
@uppfinnarn can do; do I check out the latest version on that branch or a specific version?
I'll do a normal build and a "rewrite" build.

**Comment by SoftwareGuy** [comment]
On my fork, updated to all the latest sources (tool and viewer) and well:

![image](https://cloud.githubusercontent.com/assets/1762115/9240176/aa9d68bc-41a6-11e5-9861-9e3632a57995.png)

Wait... I got an errorcat just a moment ago when I enabled the "English Translation", but noticed "Cookie Hack" was enabled... I disabled that and reset, no more errorcat after gane loads.

Not boasting my shipgirls here, but just going to show that things are working (went for a PvP battle to confirm it works). YMMV, but at this point I'm tempted to give you a package from my fresh build.

![image](https://cloud.githubusercontent.com/assets/1762115/9240209/f060989c-41a6-11e5-8bba-278a0fda45c7.png)
![image](https://cloud.githubusercontent.com/assets/1762115/9240229/3782f9cc-41a7-11e5-809d-96197269f958.png)
![image](https://cloud.githubusercontent.com/assets/1762115/9240255/8e185142-41a7-11e5-8e92-1c957c99fffd.png)

Seems to be working for me at least...

Rewrite build coming up in a few. Need to switch branches.

**Comment by SoftwareGuy** [comment]
Rewrite build failed. [Error log](https://gist.github.com/SoftwareGuy/df8a73a01c642b6750ed).

**Comment by joshmackey** [comment]
I'm running a modified 0.9.4 build (same as 0.9.4 but translation source was changed) that only started getting the errorcat when the new event started. I just attributed it to the servers being busy.

**Comment by SoftwareGuy** [comment]
Can anyone try [this build](http://cache.coburnsdomain.com/kct/KCT-095r2-SGTest.zip) that I've uploaded? It's 0.9.5 from my fork but with all the tool and viewer submodules in-sync with upstream (this repo). This is what I'm using atm, and it's working fine here. I'll shoot DMM if it's as simple fix as the cookie screwing us over.

**Comment by kevin01523** [comment]
@strongestFairy i did clone from 3 commits behind i checked the hashes and pushed it to my fork but older versions of viewer and tool were pulled. i did change some code on the kvtranslator but thats about it nothing more nothing less

**Comment by Yukariin** [comment]
>  I got an errorcat just a moment ago when I enabled the "English Translation", but noticed "Cookie Hack" was enabled... I disabled that and reset, no more errorcat after game loads.

Cookie hack affected only for dmm requests https://github.com/KanColleTool/kct-viewer/blob/master/src/KVNetworkAccessManager.cpp#L30
We not have any permanent cookie storage, so by default this cookie is not set.

> Considering DMM DID change the cookies detailed here on the English Wikia we might need to apply that fix.

I checked it now. And this still sets it's at the same way. Domain `.dmm.com`, path `/` and expiration time is one year.

Furthermore rewrite branch currently doesn't have translation and cookie hack, but I still get catscreen.

**Comment by Yukariin** [comment]
> Rewrite build failed. Error log.

Seems like you use not latest (5.5) Qt version that contains `QSslPreSharedKeyAuthenticator`.

**Comment by uppfinnarn** [comment]
Just comment out the PSK stuff, it's just a forward (I copied all the signals from the manual, which is for 5.5).

What happens if you outright comment out the `webView->setNetworkAccessManager(…);` line? That'll bypass all the custom interception we do and fall back to Qt's built-in stuff.

**Comment by Yukariin** [comment]
> What happens if you outright comment out the webView->setNetworkAccessManager(…); line? That'll bypass all the custom interception we do and fall back to Qt's built-in stuff.

I tried this earlier. Tried default QWebView QNAM and set new QNAM manually - nothing changed.

**Comment by Yukariin** [comment]
Oh, wait! Seems working!
![2015-08-13-141045_957x738_scrot](https://cloud.githubusercontent.com/assets/6450725/9248533/29409dce-41c5-11e5-9b04-a150317c0ad2.png)

I'll test it more...

**Comment by Yukariin** [comment]
Nope, sorry.
![2015-08-13-141755_959x736_scrot](https://cloud.githubusercontent.com/assets/6450725/9248645/2ab279c4-41c6-11e5-92dd-94303da5f1a5.png)

**Comment by strongestFairy** [comment]
I can confirm than build made by @SoftwareGuy is stable on Win7x64. It's behavior is the same as kevin's build: an outgoing SYN packet (a new network connection) before incoming RST packet from server.

**Comment by kevin01523** [comment]
welp cannot build the rewrite 
'''
Error	1	error C2440: 'initializing' : cannot convert from 'initializer-list' to 'QList<QNetworkRequest::Attribute>'	C:\Users\kevin0152\Documents\GitHub\kct-viewer\src\KVNetworkReply.cpp	49	1	KVBase

Error	2	error C2440: 'initializing' : cannot convert from 'initializer-list' to 'QList<QString>'	C:\Users\kevin0152\Documents\GitHub\kct-viewer\src\KVTranslator.cpp	62	1	KVBase

Error	3	error LNK1104: cannot open file 'C:\Users\kevin0152\Documents\GitHub\kct-viewer\bin\Debug\KVBase.lib'	C:\Users\kevin0152\Documents\GitHub\kctrewrite\src\LINK	KCTViewer

	4	IntelliSense: no instance of constructor "QList<T>::QList [with T=QNetworkRequest::Attribute]" matches the argument list
            argument types are: (QNetworkRequest::Attribute, QNetworkRequest::Attribute, QNetworkRequest::Attribute, QNetworkRequest::Attribute, QNetworkRequest::Attribute, QNetworkRequest::Attribute, QNetworkRequest::Attribute)	c:\Users\kevin0152\Documents\GitHub\kct-viewer\src\KVNetworkReply.cpp	41	61	KVBase

'''

i dont know if just the effect  of my system on jp locale

https://www.mediafire.com/?tmocx6hnqb6pbdt heres a unmodified build of the latest viewer linked on the master i cannot build the tool due to incompatibility to build in jp locale just finished e2 hard

compiler and tools
vs studio 2013 RTM
qt 5.5 vs2013
cmake 330

**Comment by SoftwareGuy** [comment]
What is this RST packet that we get bowled over on? Is it the one that causes "Connection Reset by Peer"?

**Comment by uppfinnarn** [comment]
Yes, it's a TCP packet. We're talking networking on the layer below HTTP here.

An `RST` packet terminates a connection on the spot, and I'm extremely confused by what could be causing it. To the application, it looks like the connection failed due to a network hiccup (with a message along the lines of "connection reset by peer"), and this is when KanColle throws up the cat screen.

For some reason, we're getting RST packets seemingly at random.

**Comment by SoftwareGuy** [comment]
Do the RST packets occur in Chrome or Firefox? And we can't poke DMM or the KC staff about the issue, because they'll likely just drop a blanket "you shouldn't be looking at network traffic" statement, can we?

I got a feeling that it may be DMM being DMM but... hmm. I'm not sure myself - I'm not a networking expert (although I can use Wireshark).

**Comment by Yukariin** [comment]
> Do the RST packets occur in Chrome or Firefox?

Latest IE in W10 that using KCV!:
![capture](https://cloud.githubusercontent.com/assets/6450725/9269530/478494d0-4273-11e5-92a7-aacef1375521.PNG)

**Comment by uppfinnarn** [comment]
Does the surrounding traffic look any different, just in case this is a red herring and we're chasing shadows with the RST packets?

**Comment by Yukariin** [comment]
@uppfinnarn on windows it's looks like server send 3 RST after EVERY API-request.
But I can mistake, need more traces.

**Comment by SoftwareGuy** [comment]
I'm about to hit the bed, do you want me to run a wireshark on my connection or do we have enough traces? If you want me to, I can do one in the morning.

**Comment by SunDwarf** [comment]
On 14/08/15 12:28, SoftwareGuy wrote:
> I'm about to hit the bed, do you want me to run a wireshark on my 
> connection or do we have enough traces? If you want me to, I can do
> one in the morning.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/KanColleTool/KanColleTool/issues/128#issuecomment-131082639>.
>
> 
If possible, could somebody run the connection through a proxy server,
that prints the results?

Here's one I found online, just sudo ./proxy.py 80 125.whatever 80 and
update your API key to point to localhost.

```
"""
usage 'pinhole port host [newport]'

Pinhole forwards the port to the host specified.
The optional newport parameter may be used to
redirect to a different port.

eg. pinhole 80 webserver
    Forward all incoming WWW sessions to webserver.

    pinhole 23 localhost 2323
    Forward all telnet sessions to port 2323 on localhost.
"""

import sys
from socket import *
from threading import Thread
import time

LOGGING = 1

def log( s ):
    if LOGGING:
        print('%s:%s' % ( time.ctime(), s ))
        sys.stdout.flush()

class PipeThread( Thread ):
    pipes = []
    def __init__( self, source, sink ):
        Thread.__init__( self )
        self.source = source
        self.sink = sink

        log( 'Creating new pipe thread  %s ( %s -> %s )' % \
            ( self, source.getpeername(), sink.getpeername() ))
        PipeThread.pipes.append( self )
        log( '%s pipes active' % len( PipeThread.pipes ))

    def run( self ):
        while 1:
            try:
                data = self.source.recv( 1024 )
                if not data: break
                print(data.decode())
                self.sink.send( data )
            except:
                break

        log( '%s terminating' % self )
        PipeThread.pipes.remove( self )
        log( '%s pipes active' % len( PipeThread.pipes ))

class Pinhole( Thread ):
    def __init__( self, port, newhost, newport ):
        Thread.__init__( self )
        log( 'Redirecting: localhost:%s -> %s:%s' % ( port, newhost,
newport ))
        self.newhost = newhost
        self.newport = newport
        self.sock = socket( AF_INET, SOCK_STREAM )
        self.sock.bind(( '', port ))
        self.sock.listen(5)

    def run( self ):
        while 1:
            newsock, address = self.sock.accept()
            log( 'Creating new session for %s %s ' % address )
            fwd = socket( AF_INET, SOCK_STREAM )
            fwd.connect(( self.newhost, self.newport ))
            PipeThread( newsock, fwd ).start()
            PipeThread( fwd, newsock ).start()

if __name__ == '__main__':

    print('Starting Pinhole')

    import sys

    if len( sys.argv ) > 1:
        port = newport = int( sys.argv[1] )
        newhost = sys.argv[2]
        if len( sys.argv ) == 4: newport = int( sys.argv[3] )
        Pinhole( port, newhost, newport ).start()
```

**Comment by uppfinnarn** [comment]
On OSX, I seem to be able to play just fine (when testing the rewrite branch) as well... o.O

Also @SunDwarf, what would be the advantage of that over Wireshark dumps?

**Comment by SunDwarf** [comment]
A more legible way of seeing the HTTP requests go through

Maybe DMM just hates the client but is fine with a proxy I dunno

**Comment by SoftwareGuy** [comment]
Let me try that and I'll get back to you.

**Comment by kyusang600** [comment]
@uppfinnarn 

OSX Viewer, Version 9.4 and 9.5 are both catbombing at really inconvenient times. Usually it catbombs when I accept the completion of a quest, change shipgirls etc.

I'm not really that strong in networking but I think DMM is changing how it deals with it's connection messing up the api-link system.

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 15/08/15 08:27, kyusang600 wrote:
> @uppfinnarn <https://github.com/uppfinnarn>
> 
> OSX Viewer, Version 9.4 and 9.5 are both catbombing at really 
> inconvenient times. Usually it catbombs when I accept the
> completion of a quest, change shipgirls etc.
> 
> I'm not really that strong in networking but I think DMM is
> changing how it deals with it's connection messing up the api-link
> system.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/KanColleTool/KanColleTool/issues/128#issuecomment-
131312415>.
>
> 
The API hasn't changed. That would fuck everything up everywhere, and
as far as I know, it hasn't. Also, if the routes changed, the server
would send 404s or their weird api error svdata stuff.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iKEEARMKAAYFAlXPCsUACgkQSn/y6UVAdgSYrwIHfkoJyHGjfS6E7ii1sfrLwJxl
6/3dANjk2UNzgrf1wMV/gQxwIzVYYfknuuhOlZ5S/3DCALyvDUmquAEOO0CmV6IC
CQGKx/Bz+LZphYcbJz9X320ETt9a8R7XssVxJ6UtU/VmbpH+Xg8nql37EwGbB2KR
GrC+2ytyjD68+N5n76mwJh3SGQ==
=i2df
-----END PGP SIGNATURE-----

**Comment by kyusang600** [comment]
@SunDwarf 

I mean like the developers might be testing some new networking protocols to possibly minimise server load. That might explain the strange RST packets we are receiving when running a WireShark.

Food For Thought :3

**Comment by uppfinnarn** [comment]
@kyusang600 It… doesn't really work like that.

We're not actually calling any endpoints - we just wrap the game client's networking facilities. And this seems to happen even when we disable that wrapping, which makes it even more confusing.

It's also communicating over standard TCP and HTTP, which kinda limits what the weird stuff you can do.

**Comment by kyusang600** [comment]
@uppfinnarn 

Sorry about my blabber. Just speculating. Y'know what I mean :3

Always a possibility :3

**Comment by SoftwareGuy** [comment]
@SunDwarf SHA512 Email signatures :open_mouth:

That pinhole thing seems to be slow as hell or it just causes a white screen without anything loaded. I've got it on my devbox, and I've pointed the viewer to the box IP address with the rest of the string that it wants which seems to forward it onto DMM. Dump for people to check out:
![image](https://cloud.githubusercontent.com/assets/1762115/9292400/e15af622-4439-11e5-993c-78f01ea03ef4.png)

*Do you really think I'd give you my API key? Sorry, have a tenryuu instead. :smile:*

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 16/08/15 08:12, SoftwareGuy wrote:
> @SunDwarf <https://github.com/SunDwarf> SHA512 Email signatures
> :open_mouth:
> 
> That pinhole thing seems to be slow as hell or it just causes a
> white screen without anything loaded. I've got it on my devbox, and
> I've pointed the viewer to the box IP address with the rest of the
> string that it wants which seems to forward it onto DMM. Dump for
> people to check out: image 
> <https://cloud.githubusercontent.com/assets/1762115/9292400/e15af622-4439-11e5-993c-78f01ea03ef4.png>
>
>  /Do you really think I'd give you my API key? Sorry, have a
> tenryuu instead. :smile:/
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/KanColleTool/KanColleTool/issues/128#issuecomment-131496167>.
>
> 
Hmm.

One thing I noticed in my own dumps is that whenever it drops, *nothing*
is being sent. No TCP packets, no HTTP requests, nothing.


-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iKEEARMKAAYFAlXQO3UACgkQSn/y6UVAdgT1ggIJAfyz2PtsPR7rYKJ30X2IE8s/
+ieYxV1UNkr13/eLjCRj5TT28Zdm/vRjM9udsMQ7P6nT5vwkty3yd2uTZmFOq2NA
Agj2nHljQfRPmn9Pr8JFnMPVOeH26vYRwQZh6uaCCDXIbs3UxrLH9J4zPmxfM7nn
edhA7oV74SJzwbGDVI/bcytXaA==
=sn9S
-----END PGP SIGNATURE-----

**Comment by SoftwareGuy** [comment]
One error cat experienced now which was caused by me having 1 quest active, and selecting page 5 of the quest log. After resetting, going directly to page 5 causes errorcat to appear. I'm not sure what the error returned is, I don't have Wireshark installed atm on this machine (it's not my home office workstation).

**Comment by uppfinnarn** [comment]
If you could get us a couple of Wireshark dumps, maybe we could spot a pattern of some kind...

**Comment by Rhextian** [comment]
guys, how often u guys getting catbomb? im only getting 2-4 catbomb the whole day w/ my own build

**Comment by SoftwareGuy** [comment]
I'll get some dumps for you @uppfinnarn later today. That is if I can get it to carbomb... It's really random. As for @Rhextian, I sometimes get them every so often, sometimes the game will be fine for my play session.

**Comment by SoftwareGuy** [comment]
Okay, here's a trace of the latest catbomb when I clicked on an admiral in PvP to battle. Note after the POST, I got the catbomb and it just died. No response back.

What I'm not sure about is the Dupe ACK...

![image](https://cloud.githubusercontent.com/assets/1762115/9299718/10fc28f6-4502-11e5-8aa6-4b1f6241c5b5.png)

Is there a specific filter you want me to do?

**Comment by strongestFairy** [comment]
@kevin01523 I played during 4 hours on your latest 9.5 build (win7x64) and not faced any catbomb. Could you point the source code version which you used for this build?

I believe than someone should try to compile and run it with another OS.

**Comment by kevin01523** [comment]
https://github.com/KanColleTool/kct-viewer/tree/394271d008a9d87c5e286738a1fc89b146b29cf9 @strongestFairy

**Comment by SunDwarf** [comment]
If this is a compiler error I am going to laugh

**Comment by SoftwareGuy** [comment]
I compiled 0.9.5. I didn't change anything above that commit, I only submitted a cmake fix and that was pulled into the official repo to bring my fork and the main repo in sync.

No other code was touched, apart from updating the submodules. Now, maybe there's a mixmatch between the submodules when I built the release then that could happen and something's firing when it shouldn't or the other way around. I don't know.

I'll git clone what kevin said "works" and test on my end. If it works, then I screwed up.

**Comment by kevin01523** [comment]
just asking what actions do the majority when the catbombing occurs i re-cloned it many times but i do not necessarily experience catbombing of any sort
i did even 
git reset --hard origin/master
git clean -f -d
git submodule foreach "git checkout master; git pull
git submodule foreach git reset --hard HEAD
git submodule foreach git clean -f -x -d
to make sure my copy is clean and updated

**Comment by SunDwarf** [comment]
What compiler do you use?

**Comment by kevin01523** [comment]
http://i.imgur.com/SFioxkP.jpg
and the latest qt 5.5

**Comment by SoftwareGuy** [comment]
I use VS Community 2013 Update 4. I use community because Ultimate is too ultimate for my blood.
I'm about to update it to Update 5 as have been putting it off.

**Comment by kevin01523** [comment]
i just have updated to update 5 a few days ago so the one i used at my last build that @strongestFairy uses was from the ultimate RTM and encountered those error C2440 on the rewrite branch

**Comment by SoftwareGuy** [comment]
Yeah, I encountered the same issue with the C2440.

**Comment by kevin01523** [comment]
![KCT 0.9.5 qt 5.5.0](http://i.imgur.com/8DhEAub.jpg)

here's my latest clean build including a installer build
https://www.mediafire.com/folder/o8k6mdsb0mqfb/KCT
zip uploaded installer still uploading on the same folder
short hashes of submodules checked out and compiled

Entering 'macviewer'
HEAD is now at 1592cfd blah
Entering 'tool'
HEAD is now at 006f234 0.9.5 bump
Entering 'viewer'
HEAD is now at 4c91058 Merge pull request #6 from SoftwareGuy/patch-1

compiling steps 
cleaned and updated modules using 
git checkout master
git pull origin master
git reset --hard origin/master
git clean -f -x -d
git submodule foreach git reset --hard HEAD
git submodule update
git submodule foreach "git checkout master; git pull"
git submodule foreach git clean  -f -x -d

opened cmake gui
set qt directories
configure then generate
runs winbuild.bat
copies readme.txt into 
/dist/KancolleTool

runs winbuild installer

**Comment by kyusang600** [comment]
I don't know if this is useful in any way but when I'm playing at my Campus (Heavily Filtered), I don't get any catbombs for some reason.

Instead it just takes a bit longer to load the specific screen (Re-Supply).

Just throwing it out there. This is Mac OSX KCTV version 9.5 btw.

**Comment by SoftwareGuy** [comment]
I get random catbombs on my NBN Wireless connection (Wireless ADSL2, using TD-LTE tech). At this point I'm putting up with the catbombs. I'm too busy to compile a new version of KCT right now.

@kevin01523 do me a favor and build a version of KCT off my fork without any changes applied by yourself. The reason I ask is because you seem to be the lucky one without catbombs, and I want someone else to ensure that the catbomb isn't specific to my build. I'll be surprised if my Visual Studio is what's causing this catbomb with the official build that I did.

**Comment by kevin01523** [comment]
'''C:\Users\kevin0152\Documents\GitHub>git clone --recursive https://github.com/SoftwareGuy/KanColleTool
Cloning into 'KanColleTool'...
remote: Counting objects: 3831, done.
remote: Total 3831 (delta 0), reused 0 (delta 0), pack-reused 3831 eceiving objects:  99% (3793/3831), 36.06 MiB | 119.0Receiving objects: 100% (3831/3831), 36.07 MiB | 121.00 KiB/s, done.

Resolving deltas: 100% (2401/2401), done.
Checking connectivity... done.
Submodule 'tool' (https://github.com/KanColleTool/kct-tool.git) registered for path 'tool'
Submodule 'viewer' (https://github.com/KanColleTool/kct-viewer.git) registered for path 'viewer'
Cloning into 'tool'...
remote: Counting objects: 2016, done.
remote: Total 2016 (delta 0), reused 0 (delta 0), pack-reused 2016
Receiving objects: 100% (2016/2016), 1.09 MiB | 128.00 KiB/s, done.
Resolving deltas: 100% (1370/1370), done.
Checking connectivity... done.
Submodule path 'tool': checked out '006f234c182451f77d738727353ac535c14bd760'
Submodule 'lib/ehttp' (https://github.com/ehttp/ehttp.git) registered for path 'lib/ehttp'
Submodule 'lib/gntp-send' (https://github.com/mattn/gntp-send.git) registered for path 'lib/gntp-send'
Cloning into 'lib/ehttp'...
remote: Counting objects: 1187, done.
remote: Total 1187 (delta 0), reused 0 (delta 0), pack-reused 1187
Receiving objects: 100% (1187/1187), 231.00 KiB | 144.00 KiB/s, done.
Resolving deltas: 100% (738/738), done.
Checking connectivity... done.
Submodule path 'tool/lib/ehttp': checked out '2d2774fc156db7c43e1b2bef3d346e5a2ee9afcd'
Submodule 'vendor/asio' (https://github.com/chriskohlhoff/asio.git) registered for path 'vendor/asio'
Submodule 'vendor/catch' (https://github.com/philsquared/Catch.git) registered for path 'vendor/catch'
Submodule 'vendor/http-parser' (https://github.com/joyent/http-parser.git) registered for path 'vendor/http-parser'
Cloning into 'vendor/asio'...
remote: Counting objects: 37286, done.
remote: Total 37286 (delta 0), reused 0 (delta 0), pack-reused 37286
Receiving objects: 100% (37286/37286), 15.40 MiB | 185.00 KiB/s, done.
Resolving deltas: 100% (21430/21430), done.
Checking connectivity... done.
Submodule path 'tool/lib/ehttp/vendor/asio': checked out '8482b59726310bc6b11cfc763b398b20bc8d25de'
Cloning into 'vendor/catch'...
remote: Counting objects: 10606, done.
remote: Total 10606 (delta 0), reused 0 (delta 0), pack-reused 10606
Receiving objects: 100% (10606/10606), 4.60 MiB | 50.00 KiB/s, done.
Resolving deltas: 100% (5833/5833), done.
Checking connectivity... done.
Submodule path 'tool/lib/ehttp/vendor/catch': checked out '338534491a72c42b0173846c4ef27452b2d14e44'
Cloning into 'vendor/http-parser'...
remote: Counting objects: 1385, done.
remote: Total 1385 (delta 0), reused 0 (delta 0), pack-reused 1385
Receiving objects: 100% (1385/1385), 502.34 KiB | 156.00 KiB/s, done.
Resolving deltas: 100% (841/841), done.
Checking connectivity... done.
Submodule path 'tool/lib/ehttp/vendor/http-parser': checked out '8d9e5db981b623fffc93657abacdc80270cbee58'
Cloning into 'lib/gntp-send'...
remote: Counting objects: 657, done.
remote: Total 657 (delta 0), reused 0 (delta 0), pack-reused 657
Receiving objects: 100% (657/657), 119.56 KiB | 152.00 KiB/s, done.
Resolving deltas: 100% (337/337), done.
Checking connectivity... done.
Submodule path 'tool/lib/gntp-send': checked out '93b184642081295c1487d71dbcdbbd382e03dda8'
Cloning into 'viewer'...
remote: Counting objects: 1936, done.
remote: Total 1936 (delta 0), reused 0 (delta 0), pack-reused 1936
Receiving objects: 100% (1936/1936), 803.10 KiB | 159.00 KiB/s, done.
Resolving deltas: 100% (1299/1299), done.
Checking connectivity... done.
fatal: reference is not a tree: ac8de2721dbe4a95c1b255f22d66e0e6f7b4a7bd
Unable to checkout 'ac8de2721dbe4a95c1b255f22d66e0e6f7b4a7bd' in submodule path 'viewer'
'''

cannot clone from your fork completely

**Comment by uppfinnarn** [comment]
Something just struck me: try building without the XP compatibility thing (the `CMAKE_GENERATOR_TOOLSET` property). Just comment out [this line](https://github.com/KanColleTool/kct-viewer/blob/master/CMakeLists.txt#L6), run `git clean -ffdx && git submodule foreach git clean -ffdx` and try re-building.

It's a long shot, but it just may be the culprit. A bizarre issue just may have a bizarre explanation.

**Comment by kevin01523** [comment]
ive been using the 
win xp like ages ago on my builds
but most of the time i put it under
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${PROJECT_SOURCE_DIR}/bin")
well i also build the one from the origin/master without changing anything and im not getting any catbombs
well its worth a shot.

**Comment by SoftwareGuy** [comment]
@kevin01523 that reference is not a tree baffles me... Unless it means my submodule is at a higher commit than upstream which is likely.

If the XP thing fixes the catbombs, then perhaps we can axe XP Support.

**Comment by kevin01523** [comment]
@SoftwareGuy  well since my builds is not affected by catbombs i have no way to test if that affects it try my latest build as its a clean build out of origin/master ugh im still stuck at e3

**Comment by SoftwareGuy** [comment]
@kevin01523 OK, I'll test your build.

**Comment by SoftwareGuy** [comment]
@kevin01523 Okay. What black magic does yours have that mine doesn't? It seems your build is not erroring so far, and I've just done some modernization. Going to run a sortie to see if it's still "fixed". I'm not sure what to point the finger to... Unless QT 5.5 fixed the issues.

**Comment by uppfinnarn** [comment]
@SoftwareGuy …please don't tell me we've been chasing ghosts caused by an outdated library.

**Comment by SunDwarf** [comment]
https://bugreports.qt.io/browse/QTBUG-46859 ?

**Comment by kevin01523** [comment]
ok im testing my old build which is on 0.9.4 and on qt 5.3. with broken translation(fixed when i added openssl libraries https://indy.fulgan.com/SSL/openssl-1.0.2d-i386-win32.zip)it uses the https:// url for the translation from yukariins repo

and i experienced about 5 cat bombs within 30 minutes

so i can say that some changes on the KC server like transferring from apache to nginx or etc caused a catbombs spree on kctviewer builds on qt5.3+ but not on 5.5

**Comment by SunDwarf** [comment]
Judging from this, the cause seems to be QT versions less than 5.5. 90-something comments later, we find the cause, and it's Qt's fault!

**Comment by uppfinnarn** [comment]
@kevin01523 s**O ABOUT THOSE _DIRECT LINKS…_**

@SunDwarf THIS EXPLAINS EVERYTHING

Does it still happen when the Windows version is built with the latest Qt version? For the Linux version, we may need to use the `Qt::QueuedConnection` workaround if the packages in circulation are too outdated.

**Comment by SoftwareGuy** [comment]
@uppfinnarn honestly, I don't know why it would be caused by outdated library. I went with a sane assumption of using 5.3.2 which I think was the stable before 5.5 came put. Could be wrong.

I will update to 5.5 and then do a clean build to see if I can get a working replica of Kevin's build.
I got an errorcat twice using his build but the occurrence of them dropped a lot.

Expect a test build later today. If it's all functional, I'll build 0.9.5p1 that uses Qt 5.5.
Am I at fault for using the outdated 5.3.2 version?

**Comment by uppfinnarn** [comment]
@SoftwareGuy Yes. If something behaves weirdly, and it's built on top of something outdated, UPDATE IT. Always. Chances are, you just fixed it without lifting a finger.

**Comment by SoftwareGuy** [comment]
@uppfinnarn I'm glad I view you as a mentor, you have some very good views when it comes to programming.

Anyhow:
**Version 0.9.5b - "Thanks for breaking things, QT!" edition**
OpenSSL included. No errorcats so far (currently doing a test sortie with Tenryuu's Kindergarden).

*Downloads*
Unpack and run: http://cache.coburnsdomain.com/kct/KCT_095p1.zip
Installer: http://cache.coburnsdomain.com/kct/KCT_095p1_Setup.exe

I'll remove the URLs as soon as these are on the official site. Just for reference, should you want to look at my mirror, just look at http://cache.coburnsdomain.com/kct/ . All the builds I do for testing and/or debugging issues will be put there. That URL won't vanish anytime soon since it's part of my business domains.

**Comment by SunDwarf** [comment]
Okay, that's confirmation enough.

**Comment by uppfinnarn** [comment]
Oh, great, this got closed so I never noticed that reply. Please don't do that again.

@SoftwareGuy, please rebuild that as 0.9.6.

**Comment by SoftwareGuy** [comment]
@uppfinnarn no problems, I'll crank a build out either later today or have it done for you tomorrow.
I won't mess around with my current workstation setup as I've had enough of it being ***tsundere*** so I'll build it in a Windows 7 VM.

**Comment by SoftwareGuy** [comment]
Okay. Took longer than expected, a 30GB disk image really doesn't cut the cake when you install a fresh Windows 7 + VS 2013 Community + QT 5.5 + Git, C-Make and friends.

Installer: http://cache.coburnsdomain.com/kct/KanColleTool_0.9.6_Setup.exe
Unpack and Run: http://cache.coburnsdomain.com/kct/KanColleTool_0.9.6.zip

Request for @uppfinnarn, you'll have to update the version in CMakeLists.txt in your repo to 0.9.6 manually, I have a suspicion that I need to clone the submodules and remap their locations to my github (I get 403 denied otherwise since I have no write access to the respective repos here). I'm in no mood to do so right now, however the binaries above have 0.9.6 version string. Compiled with QT 5.5 and has SSL binaries as well. No other modifications made. Should just work.

**Comment by kevin01523** [comment]
hmm the viewer on the main repo is not updated also the one on the kancolletool.github.io download

**Comment by sauyon** [comment]
@SoftwareGuy trying to do the update atm.
Damn all these submodules >.>

**Comment by liclac** [comment]
0.9.6 actually got released! (thanks @sauyon)
I'll close this unless the problem persists
